apiVersion: v1
data:
  setenv.sh: |
    export CATALINA_OPTS="$CATALINA_OPTS -Xms512m"
    export CATALINA_OPTS="$CATALINA_OPTS -Xmx8192m"
    export CATALINA_OPTS="$CATALINA_OPTS -XX:MaxPermSize=256m"

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: setenv-config
